//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.29 at 11:12:30 AM CEST 
//

package psidev.psi.pi.rulefilter.jaxb;

import javax.xml.bind.annotation.XmlRegistry;

/**
 * This object contains factory methods for each Java content interface and Java
 * element interface generated in the psidev.psi.ms.rulefilter.jaxb package.
 * <p>
 * An ObjectFactory allows you to programatically construct new instances of the
 * Java representation for XML content. The Java representation of XML content
 * can consist of schema derived interfaces and classes representing the binding
 * of schema type definitions, element declarations and model groups. Factory
 * methods for each of these are provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

	/**
	 * Create a new ObjectFactory that can be used to create new instances of
	 * schema derived classes for package: psidev.psi.ms.rulefilter.jaxb
	 * 
	 */
	public ObjectFactory() {
	}

	/**
	 * Create an instance of {@link RuleConditions }
	 * 
	 */
	public RuleConditions createRuleConditions() {
		return new RuleConditions();
	}

	/**
	 * Create an instance of {@link RulesToSkipRef }
	 * 
	 */
	public RulesToSkipRef createRulesToSkipRef() {
		return new RulesToSkipRef();
	}

	/**
	 * Create an instance of {@link UserCondition }
	 * 
	 */
	public UserCondition createUserCondition() {
		return new UserCondition();
	}

	/**
	 * Create an instance of {@link RuleCondition }
	 * 
	 */
	public RuleCondition createRuleCondition() {
		return new RuleCondition();
	}

	/**
	 * Create an instance of {@link UserOption }
	 * 
	 */
	public UserOption createUserOption() {
		return new UserOption();
	}

	/**
	 * Create an instance of {@link ReferencedRules }
	 * 
	 */
	public ReferencedRules createReferencedRules() {
		return new ReferencedRules();
	}

	/**
	 * Create an instance of {@link MandatoryElements }
	 * 
	 */
	public MandatoryElements createMandatoryElements() {
		return new MandatoryElements();
	}

	/**
	 * Create an instance of {@link RuleToSkip }
	 * 
	 */
	public RuleToSkip createRuleToSkip() {
		return new RuleToSkip();
	}

	/**
	 * Create an instance of {@link References }
	 * 
	 */
	public References createReferences() {
		return new References();
	}

	/**
	 * Create an instance of {@link UserConditions }
	 * 
	 */
	public UserConditions createUserConditions() {
		return new UserConditions();
	}

	/**
	 * Create an instance of {@link RuleFilter }
	 * 
	 */
	public RuleFilter createRuleFilter() {
		return new RuleFilter();
	}

	/**
	 * Create an instance of {@link MandatoryElement }
	 * 
	 */
	public MandatoryElement createMandatoryElement() {
		return new MandatoryElement();
	}

}
